### ISSUE TITLE
[13.0] connector_jira_servicedesk - Error message during the Installation

### ISSUE THREAD

**Issue by yboujraf** [OCA/connector-jira#69]
Dear @rvalyi , @ovnicraft , @pniederlag , @cmayo , @christophlsa 

- Ubuntu 20.04.02 server
- Odoo 13 CE

I have installed successfully the connector-jira and linked with Jira.

Now, Trying to install the Connector_jira_servicedesk, I have got an error after selecting "Install"

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1343, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-59>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 421, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo/odoo-server/odoo/modules/loading.py", line 313, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo/odoo-server/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/odoo/odoo-server/odoo/modules/module.py", line 376, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/odoo/custom/addons/connector_jira_servicedesk/__init__.py", line 1, in <module>
    from . import models
  File "/odoo/custom/addons/connector_jira_servicedesk/models/__init__.py", line 4, in <module>
    from . import jira_organization
  File "/odoo/custom/addons/connector_jira_servicedesk/models/jira_organization/__init__.py", line 3, in <module>
    from . import adapter
  File "/odoo/custom/addons/connector_jira_servicedesk/models/jira_organization/adapter.py", line 30, in <module>
    class OrganizationAdapter(Component):
  File "/odoo/custom/addons/connector_jira_servicedesk/models/jira_organization/adapter.py", line 39, in OrganizationAdapter
    CaseInsensitiveDict({"X-ExperimentalApi": "opt-in"})
  File "/usr/local/lib/python3.8/dist-packages/jira/utils/__init__.py", line 41, in __init__
    for key, value in super(CaseInsensitiveDict, self).items():
RuntimeError: dictionary keys changed during iteration
```

**Comment by yboujraf** [comment]
Dear @leemannd

This is the screenshots of the "connector-jira" installed

### Modules

![image](https://user-images.githubusercontent.com/6151258/118945765-0ceb3800-b956-11eb-8f93-20a50ee694fb.png)

- Regarding "connector-jira

![image](https://user-images.githubusercontent.com/6151258/118945512-cf86aa80-b955-11eb-8abc-a2efedfc044a.png)

![image](https://user-images.githubusercontent.com/6151258/118945588-e0372080-b955-11eb-9194-180f74b45fcd.png)

- Only "connector_jira_servicedesk" doesn't want to be installed.

![image](https://user-images.githubusercontent.com/6151258/118944975-55562600-b955-11eb-9613-7783fbaf5343.png)

![image](https://user-images.githubusercontent.com/6151258/118945042-60a95180-b955-11eb-8873-1efc7ba0af9d.png)

### Log

2021-05-20 08:28:31,220 4334 INFO test werkzeug: 192.168.0.230 - - [20/May/2021 08:28:31] "POST /web/dataset/call_kw/ir.module.module/read HTTP/1.1" 200 - 7 0.005 0.030
2021-05-20 08:28:31,274 4334 INFO test werkzeug: 192.168.0.230 - - [20/May/2021 08:28:31] "POST /web/dataset/call_kw/ir.module.module.dependency/read HTTP/1.1" 200 - 5 0.003 0.006
2021-05-20 08:28:40,891 4334 INFO test odoo.addons.base.models.ir_module: ALLOW access to module.button_immediate_install on ['connector_jira_servicedesk'] to user info@xxx.be #2 via 192.168.0.230
2021-05-20 08:28:40,891 4334 INFO test odoo.addons.base.models.ir_module: User #2 triggered module installation
2021-05-20 08:28:40,892 4334 INFO test odoo.addons.base.models.ir_module: ALLOW access to module.button_install on ['connector_jira_servicedesk'] to user info@xxx.be #2 via 192.168.0.230
2021-05-20 08:28:41,041 4334 INFO test odoo.modules.loading: loading 1 modules...
2021-05-20 08:28:41,059 4334 INFO test odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries
2021-05-20 08:28:41,214 4334 INFO test odoo.modules.loading: updating modules list
2021-05-20 08:28:41,215 4334 INFO test odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via 192.168.0.230
2021-05-20 08:28:42,199 4334 INFO test odoo.modules.loading: loading 115 modules...
2021-05-20 08:28:42,815 4334 INFO test odoo.modules.loading: 115 modules loaded in 0.62s, 0 queries
2021-05-20 08:28:42,822 4334 INFO test odoo.modules.loading: loading 116 modules...
2021-05-20 08:28:43,451 4334 CRITICAL test odoo.modules.module: Couldn't load module connector_jira_servicedesk
2021-05-20 08:28:43,451 4334 CRITICAL test odoo.modules.module: dictionary keys changed during iteration
2021-05-20 08:28:43,453 4334 WARNING test odoo.modules.loading: Transient module states were reset
2021-05-20 08:28:43,456 4334 ERROR test odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 421, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo/odoo-server/odoo/modules/loading.py", line 313, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo/odoo-server/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/odoo/odoo-server/odoo/modules/module.py", line 376, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/odoo/custom/addons/connector_jira_servicedesk/__init__.py", line 1, in <module>
    from . import models
  File "/odoo/custom/addons/connector_jira_servicedesk/models/__init__.py", line 4, in <module>
    from . import jira_organization
  File "/odoo/custom/addons/connector_jira_servicedesk/models/jira_organization/__init__.py", line 3, in <module>
    from . import adapter
  File "/odoo/custom/addons/connector_jira_servicedesk/models/jira_organization/adapter.py", line 30, in <module>
    class OrganizationAdapter(Component):
  File "/odoo/custom/addons/connector_jira_servicedesk/models/jira_organization/adapter.py", line 39, in OrganizationAdapter
    CaseInsensitiveDict({"X-ExperimentalApi": "opt-in"})
  File "/usr/local/lib/python3.8/dist-packages/jira/utils/__init__.py", line 41, in __init__
    for key, value in super(CaseInsensitiveDict, self).items():
RuntimeError: dictionary keys changed during iteration
2021-05-20 08:28:43,456 4334 ERROR test odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1343, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-60>", line 2, in button_immediate_install
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 421, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo/odoo-server/odoo/modules/loading.py", line 313, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo/odoo-server/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/odoo/odoo-server/odoo/modules/module.py", line 376, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/odoo/custom/addons/connector_jira_servicedesk/__init__.py", line 1, in <module>
    from . import models
  File "/odoo/custom/addons/connector_jira_servicedesk/models/__init__.py", line 4, in <module>
    from . import jira_organization
  File "/odoo/custom/addons/connector_jira_servicedesk/models/jira_organization/__init__.py", line 3, in <module>
    from . import adapter
  File "/odoo/custom/addons/connector_jira_servicedesk/models/jira_organization/adapter.py", line 30, in <module>
    class OrganizationAdapter(Component):
  File "/odoo/custom/addons/connector_jira_servicedesk/models/jira_organization/adapter.py", line 39, in OrganizationAdapter
    CaseInsensitiveDict({"X-ExperimentalApi": "opt-in"})
  File "/usr/local/lib/python3.8/dist-packages/jira/utils/__init__.py", line 41, in __init__
    for key, value in super(CaseInsensitiveDict, self).items():
RuntimeError: dictionary keys changed during iteration
2021-05-20 08:28:43,463 4334 INFO test odoo.modules.loading: loading 1 modules...
2021-05-20 08:28:43,483 4334 INFO test odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries
2021-05-20 08:28:43,583 4334 INFO test odoo.modules.loading: loading 115 modules...
2021-05-20 08:28:43,897 4334 INFO ? werkzeug: 192.168.0.230 - - [20/May/2021 08:28:43] "GET /web/static/src/img/spin.png HTTP/1.1" 304 - - - -
2021-05-20 08:28:44,215 4334 INFO test odoo.modules.loading: 115 modules loaded in 0.63s, 0 queries
2021-05-20 08:28:44,672 4334 INFO test odoo.modules.loading: Modules loaded.

### pip list

I see the version of the python JIRA library is 2.0.0.

Thanks if you could highlight me.

Best Regards,

**Comment by yboujraf** [comment]
Dear

I have fixed the error by uninstalling jira python package version 2 and replaced by version 3.

Best Regards
